[tool] load parameters before initializing
ros-visualization/rviz pull request #1570
Opened 2020-12-16 15:46 UTC by jcmonteiro

### Description

With this PR the tool parameters will be available when `onInitialize` is called. One can use this feature to solve #1138 by adding
an `rviz::StringProperty`, e.g. named `Tool Name`, and then use its value to rename the tool in `onInitialize`.

2020-12-17 11:48 UTC, rhaschke commented
I'm not sure about the purpose of this PR yet. Isn't it common practice to first initialize an object (display, panel, tool, ...) and later load its parameters? I don't like the idea of coupling the loading to the creation of a tool. Regarding #1138: I guess you can always call `setName()` on your tool, can't you?

2020-12-17 12:19 UTC, jcmonteiro commented
> Isn't it common practice to first initialize an object (display, panel, tool, ...) and later load its parameters?
Hmm.. I'm not quite sure. After all, the initialization might depend on the parameters. What would be the downside of having the parameters available in `onInitialize`?

> Regarding #1138: I guess you can always call `setName()` on your tool, can't you?
Calling setName has no effect after `onInitialize`. At least it has no effect when called in `activate`. Besides, `activate` takes place only when the tool is clicked, so even if it worked there the name would only change to the correct one once the tool had been clicked.

2020-12-17 13:07 UTC, rhaschke commented
> After all, the initialization might depend on the parameters.

It shouldn't. It's always possible to load a different config later. However, the initialization should always work.

> Calling `setName` has no effect after `onInitialize`.

I don't see why this should be the case. Currently, `setName()` is called just shortly before `initialize()`:
https://github.com/ros-visualization/rviz/blob/13d061d973e96c6315c7768a7f316d2cc501299d/src%2Frviz%2Ftool_manager.cpp#L235-L237

2020-12-17 13:50 UTC, jcmonteiro commented
> It shouldn't. It's always possible to load a different config later. However, the initialization should always work.

I see... I did some more digging in the code and the issue is the following with `setName` and `setIcon`: they have no effect on the menu entries because they are created only once per tool in
https://github.com/ros-visualization/rviz/blob/2fe6d33f1ca7ceccd916cea94c199ac8a2f25ca5/src/rviz/visualization_frame.cpp#L1177-L1188

From what you explained about the initialization, I believe that the proper solution to #1138 is to change the `setName` and `setIcon` methods so that they force a reload of the action and update the member variables `action_to_tool_map_`, `tool_to_action_map_`, `toolbar_`, and `remove_tool_menu_` from `VisualizationFrame`. After doing so, calling `setName` or `setIcon` from an overloaded `load` method should do the trick. What do you think?

2020-12-17 13:57 UTC, rhaschke commented
That sounds reasonable. Would it be sufficient to change the name? I think, having the same icons for the same tool, would facilitate its identification. I suggest introducing a signal `nameChanged()`, such that the VisFrame is informed about name changes.

2020-12-17 14:22 UTC, jcmonteiro commented
Completely agree. I'll do it then.

2020-12-17 15:30 UTC, jcmonteiro commented
I've force-pushed the changes. Calling `setName` now updates the toolbar and this PR solves #1138.

2020-12-17 15:58 UTC, rhaschke requested changes
Thanks for this contribution. In general, this looks good. Some minor remarks though.

2020-12-17 15:58 UTC, rhaschke commented on src/rviz/tool.cpp
>    name_ = name;
Please add a check to verify that name will actually change. If not, you can return early.

2020-12-17 15:58 UTC, rhaschke commented on src/rviz/tool.h
> +  void nameChanged(Tool* tool);
Please change the argument to `const QString&`, passing the new name. You can always access the sender of a signal by other means, namely [`QObject::sender()`](https://doc.qt.io/archives/qt-4.8/qobject.html#sender).

2020-12-17 15:58 UTC, rhaschke commented on src/rviz/visualization_frame.cpp
> +  action->setIconText(tool->getName());
Please avoid searching the map twice:
```suggestion
  auto it = tool_to_action_map_.find(sender());
  if (it == tool_to_action_map_.end())
    return;
  (*it)->setIconText(name);
```

2020-12-17 15:58 UTC, rhaschke commented on src/rviz/visualization_frame.h
> +  void updateTool(Tool* tool);
```suggestion
  void onToolNameChanged(const QString& name);
```

2020-12-18 08:19 UTC, jcmonteiro commented
Great suggestions! I've force-pushed again to meet them.

2020-12-18 11:02 UTC, rhaschke reviewed
Two more nitpicks. Otherwise looks good. Thanks.

2020-12-18 11:02 UTC, rhaschke commented on src/rviz/visualization_frame.h
> +   * @sa onToolNameChanged() */
```suggestion
  /** React to name changes of a tool, updating the name of the associated QAction */
```

2020-12-18 14:30 UTC, jcmonteiro commented
> Two more nitpicks. Otherwise looks good. Thanks.

That's completely understandable :+1:. I've pushed the changes.

2020-12-18 16:27 UTC, rhaschke approved these changes

2020-12-18 16:28 UTC, merged

2020-12-18 16:28 UTC, rhaschke commented
Thanks a lot.