Added regex filter field for TF  display
ros-visualization/rviz pull request #1744
Opened 2022-05-16 14:24 UTC by BlazPotokar

### Description

When there is a lot of frames on `/tf` it can be hard to properly visualize them in RViz especially if frames overlap. Usually solution to this is to enable and disable desired frames in `Frames` field of the `TF display`. But it quickly become very annoying task if there is a lot of frames (e.g.  100 +) and each one needs to be found in a long list first and then disabled/enabled.

Because of that I suggest adding regex field which filters frames and displays only the ones matching entered expression. For convenience I also suggest adding additional field for blacklist filter.
Benefit of this approach is that user can quickly setup one or more displays, each showing specific group of frames and he can turn each one on/off as needed.
Scene with a lot of frames ...
![image](https://user-images.githubusercontent.com/22647774/168610888-9de6f8a2-b26d-4b9d-86ff-250726e57524.png)
... can be easily filtered so only interesting frames are displayed
![image](https://user-images.githubusercontent.com/22647774/168612056-0212f0fc-3417-4904-b1a8-51885f467101.png)

Example when multiple TF displays are added. Each one has its own settings and frame filter.
![image](https://user-images.githubusercontent.com/22647774/168614669-64887ca6-c086-4af3-8250-0e971ddd4744.png)

2022-05-18 09:44 UTC, rhaschke requested changes
Thanks for this contribution. Please consider my comments.

2022-05-18 09:44 UTC, rhaschke commented on src/rviz/default_plugin/tf_display.cpp
> +#include "rviz/properties/color_property.h"
Why do you need to add ColorProperty?

2022-05-18 09:44 UTC, rhaschke commented on src/rviz/default_plugin/tf_display.cpp
> +  filter_blacklist_property_ = new StringProperty("Filter (blacklist)", "", "Regex filter", this);
I suggest moving these properties as children of `frames_category_`. This makes it clear, where the filters are applied to. However, it makes the property harder to discover. What do you think?
Please rename "Filter" -> "Filter (whitelist)".

2022-05-18 09:44 UTC, rhaschke commented on src/rviz/default_plugin/tf_display.cpp
>    std::sort(frames.begin(), frames.end());
I suggest filtering frame names before sorting them (for efficiency).

2022-05-18 09:44 UTC, rhaschke commented on src/rviz/default_plugin/tf_display.cpp
> +          if (std::regex_match(frame, blacklist_regex))
Prefer logical AND over nested IF:
```suggestion
        if (!blacklist_regex_string.empty()) && std::regex_match(frame, blacklist_regex))
```

2022-05-18 09:44 UTC, rhaschke commented on src/rviz/default_plugin/tf_display.cpp
> +                                      //  appears but is not significant and only happens when user changes fields.
This needs to be fixed!

2022-05-18 09:44 UTC, rhaschke commented on src/rviz/default_plugin/tf_display.h
> +  StringProperty* filter_property_;
Rename:
```suggestion
  StringProperty* filter_whitelist_property_;
```

2022-08-01 07:44 UTC, rhaschke commented
@BlazPotokar, do you plan to fix the remaining issues and finish this PR?

2023-03-29 13:52 UTC, merged

2023-03-29 14:26 UTC, BlazPotokar commented
Thank you so much for resolving the remaining issues!